### ISSUE TITLE
Switch from colorblind to any other users wont be colored anymore

### ISSUE THREAD

**Issue by guserav** [guserav/WebEngiMitLenni#18]

**Comment by Oswaldbob** [comment]
No, it only misses in colorblind mode on purpose. But if you switch from color blind to any other it wont color again until next reload of a chat room. 
So the bug should be called: Switch from colorblind to any other users wont be colored anymore

**Comment by Oswaldbob** [comment]
fixed, now after every change the current room will be reloaded and therefor correlcty displayed
